#!/bin/bash

containerIDs=$@
echo "arg = $containerIDs"
length=${#containerIDs}
echo "len = $length"
# 12 en bas représente le nombre de caractères dans un ID conteneur docker
if [ $length -eq 12 ]
then 
	curl -X "DELETE" 192.168.56.101:8888/api/routes/$containerIDs

elif [ $length -gt 12 ]
then
	IFS=' ' read -r -a array <<< "$containerIDs"
	for id in "${array[@]}"
	do
		echo "$id"
		curl -X "DELETE" 192.168.56.101:8888/api/routes/$id
	done
fi
