#!/bin/bash
nbContainers=$1
containers=$@
echo "arg = $containers"
length=${#containers}
echo "len = $length"
# 77 en bas représente le nombre de caractères dans un ID conteneur docker + le token associé
if [ $length -eq 77 ]
then 
	IFS=' ' read -r -a array <<< "$containers"
	curl -X "DELETE" 192.168.56.101:8888/api/routes/${array[0]}/${array[1]}

elif [ $length -gt 77 ]
then
	IFS=' ' read -r -a array <<< "$containers"
	len=${#array[@]}
	i=1
	while [ $i -lt $len ]
	do
		token_cell=$(( i + nbContainers ))
		curl -X "DELETE" 192.168.56.101:8888/api/routes/${array[i]}/${array[token_cell]}
		(( i++ ))
	done
fi
