#!/bin/bash

#sudo apt install inotify-tools
#sudo apt install libxml2-utils
#while inotifywait -r -e modify /home/user/DockerScripts/demande.xml
#do
action=$(xmllint --xpath '//action/text()' /home/user/DockerScripts/demande.xml)
if [ "$action" == "create" ]
then
	image=$(xmllint --xpath '//image/text()'  /home/user/DockerScripts/demande.xml)
	image="${image,,}" #to lower case

	#on change le nom de l'image par celui de nos propres images docker avec ssh installé
	if [ "$image" == "debian" ]
	then
		image="mydebian"
	elif [ "$image" == "centos" ]
	then
		image="mycentos"
	fi

	nb=$(xmllint --xpath '//nb/text()' /home/user/DockerScripts/demande.xml)

	echo 'Traitement du fichier demande.xml terminé !'
	#echo $action
	#echo $image
	#echo $nb
	/home/user/DockerScripts/scriptCreateContainer $nb $image	
	echo 'scriptTraiteXML terminé !'
elif [ "$action" == "destroyall" ]
then
	/home/user/DockerScripts/scriptDestroyAllContainers
fi
#done

