#!/bin/bash
nbContainers=$1
containers=$@
echo "nbCont -> $1"
echo "ALL -> $@"
        IFS=' ' read -r -a containers <<< "$containers"
	table_length=${#containers[@]}
	nb_iterations=$(( table_length - nbContainers * 2 ))
	i=1
        while [ $i -lt $nb_iterations ]
        do
		container_ip_cell=$(( i + nbContainers ))
		container_token_cell=$(( i + nbContainers * 2 ))
		
		POST 192.168.56.101:8888/api/routes/${containers[i]}/${containers[container_token_cell]} <<- EOF
		{ "target": "http://${containers[container_ip_cell]}:4200"}
		EOF
		(( i++ ))
        done

