#!/bin/bash

# n'oublier pas de creer un fichier retour.xml vide sur la machine serveurFrontal
# et donner à ce fichier les permissions de 'user' pour que ça fonctionne
scp /home/user/DockerScripts/retour.xml user@192.168.56.102:/var/www/pageDeGestion/html/retour.xml
echo 'Envoi du Fichier retour.xml terminé !'
echo 'scriptSendXML terminé !'
